### ISSUE TITLE
cant download the dataset

### ISSUE THREAD

**Issue by tongbc** [joosthub/PyTorchNLPBook#7]
connection refused...

**Comment by braingineer** [comment]
Hi @tongbc 

Are you able to access it through this link? https://drive.google.com/open?id=1o2ac0EliUod63sYUdpow_Dh-OqS3hF5Z

Sometimes firewalls block google drive links.

**Comment by tongbc** [comment]
Hi @braingineer,i can access it though ur link,can you please upload the whole project including the dataset to the google drive,so i can download and use them?thank a lot,my friend!or you can send it to my email address,624360737@qq.com  thanks alot!

**Comment by braingineer** [comment]
Hi @tongbc 

That is good you can access it through that link. It is odd that the script doesn't work.  I have edited the README to link to the datasets directly and state what the directory structure should be.  The IDs that were in the `get-all-data.sh` script were the google drive IDs and so they can be converted back to their URL form. 

Here is the link to the diff: https://github.com/joosthub/PyTorchNLPBook/commit/bbd1d0d707019578cce4affa0361272a0c420305
and you should now be able to view the links: https://github.com/joosthub/PyTorchNLPBook/tree/master/data

Please let me know if you have further issues!
