### ISSUE TITLE
Manual Data Download

### ISSUE THREAD

**Issue by sunginmkone** [joosthub/PyTorchNLPBook#9]
I am getting the following error. If I click on the manual download link.

400. That’s an error.

The requested URL was not found on this server. That’s all we know.

**Comment by sunginmkone** [comment]
Only the first link raw_train.csv works and all the rest is getting the error 400.

**Comment by govindgnair23** [comment]
I am facing the same problem

**Comment by adisharma29** [comment]
Facing the same issue

**Comment by braingineer** [comment]
hi @sunginmkone @govindgnair23 @adisharma29 
Sorry! I messed up the URLs. If you look at the first, you will see there is an 'id=' in the url that I missed on the rest. Fixing now :)
